// Code generated by controller-gen. This placeholder is intentionally checked in so the package shape is obvious.
// Run `make generate` after installing controller-gen to replace it with generated deepcopy methods.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *VultrNodeClass) DeepCopyInto(out *VultrNodeClass) {
	*out = *in
	out.ObjectMeta = *in.ObjectMeta.DeepCopy()
	if in.Spec.OSID != nil {
		out.Spec.OSID = new(int)
		*out.Spec.OSID = *in.Spec.OSID
	}
	if in.Spec.SSHKeyIDs != nil {
		out.Spec.SSHKeyIDs = append([]string(nil), in.Spec.SSHKeyIDs...)
	}
	if in.Spec.VPCIDs != nil {
		out.Spec.VPCIDs = append([]string(nil), in.Spec.VPCIDs...)
	}
	if in.Spec.EnableIPv6 != nil {
		out.Spec.EnableIPv6 = new(bool)
		*out.Spec.EnableIPv6 = *in.Spec.EnableIPv6
	}
	if in.Status.Conditions != nil {
		out.Status.Conditions = append([]metav1.Condition(nil), in.Status.Conditions...)
	}
	if in.Status.ResolvedPlanIDs != nil {
		out.Status.ResolvedPlanIDs = append([]string(nil), in.Status.ResolvedPlanIDs...)
	}
}
func (in *VultrNodeClass) DeepCopy() *VultrNodeClass {
	if in == nil {
		return nil
	}
	out := new(VultrNodeClass)
	in.DeepCopyInto(out)
	return out
}
func (in *VultrNodeClass) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *VultrNodeClassList) DeepCopyInto(out *VultrNodeClassList) {
	*out = *in
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		out.Items = make([]VultrNodeClass, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *VultrNodeClassList) DeepCopy() *VultrNodeClassList {
	if in == nil {
		return nil
	}
	out := new(VultrNodeClassList)
	in.DeepCopyInto(out)
	return out
}
func (in *VultrNodeClassList) DeepCopyObject() runtime.Object { return in.DeepCopy() }
