apiVersion: apps/v1
kind: Deployment
metadata:
  name: karpenter-provider-vultr
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karpenter-provider-vultr
  template:
    metadata:
      labels:
        app: karpenter-provider-vultr
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: VULTR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.apiKeySecret.name }}
                  key: {{ .Values.apiKeySecret.key }}
